name: Qodana Quality

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  qodana-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt install -y tree
          tree -L 1 -I '.git'

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: adopt

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v4.2.5
        with:
          linter: jetbrains/qodana-jvm-community
          fail-threshold: 100
          upload-result: true

      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./